VERSION and FULLVER

diff --git a/scripts/zupd b/scripts/zupd
--- a/scripts/zupd
+++ b/scripts/zupd
@@ -6,6 +6,7 @@ TMPDIR=/tmp/zig
 SCRIPT_NAME=$(basename "$0")
 
 REPO_ENTRY=$1
+VERSION=${2:-master}
 
 function die()
 {
@@ -28,29 +29,29 @@ mkdir -p "${TMPDIR}"
 
 echo "Downloading repository..."
 
-curl -s "${REPO_URL}" | jq ".master[\"${REPO_ENTRY}\"]" > "${REPO}" || die "failed to aquire repo!"
+curl -s "${REPO_URL}" | jq ".\"${VERSION}\"[\"${REPO_ENTRY}\"]" > "${REPO}" || die "failed to aquire repo!"
 
 TARBALL=$(jq --raw-output '.tarball' ${REPO})
 SHASUM=$(jq --raw-output '.shasum' ${REPO})
 SIZE=$(jq --raw-output '.size' ${REPO})
 
-VERSION=$(basename ${TARBALL} .tar.xz)
+FULLVER=$(basename ${TARBALL} .tar.xz)
 
 echo "$TARBALL"
-echo "$VERSION"
+echo "$FULLVER"
 
-[ "${VERSION}" != "" ] || die "Could not extract version info"
+[ "${FULLVER}" != "" ] || die "Could not extract version info"
 
-if [ $(basename $(readlink -f ${ROOT}/current)) = ${VERSION} ]; then
-	echo "${VERSION} is already the current version!"
+if [ $(basename $(readlink -f ${ROOT}/current)) = ${FULLVER} ]; then
+	echo "${FULLVER} is already the current version!"
 else
-	echo "Updating to ${VERSION}"
+	echo "Updating to ${FULLVER}"
 
 	if curl "${TARBALL}" | tar -xJC ${ROOT}/ver; then
-		ln -sfn "${ROOT}/ver/${VERSION}" "${ROOT}/current" || die "failed to set new symlink!"
+		ln -sfn "${ROOT}/ver/${FULLVER}" "${ROOT}/current" || die "failed to set new symlink!"
 	else
 		echo "Update failed!"
-		rm -rf "${ROOT}/ver/${VERSION}"
+		rm -rf "${ROOT}/ver/${FULLVER}"
 	fi
 fi
 
